services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HUSKY: 0
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    expose:
      - ${PORT}
    restart: unless-stopped
    env_file:
      - .env
